gunshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weapons-shop/', include('weapons.urls', namespace='weapons')),
    path('', RedirectView.as_view(url='weapons-shop/', permanent=True)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weapons/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import AllWeaponsView, WeaponDetailView, Contact

app_name = 'weapons'

urlpatterns = [
    path('', AllWeaponsView.as_view(), name='index'),
    path('contact/', Contact.as_view(), name='contact'),
    path('weapon/<int:pk>/', WeaponDetailView.as_view(), name='weapon_info'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "weapons.views.page_not_found_view"

weapons/models.py
from django.db import models


class Weapon(models.Model):
    """Модель оружия"""
    title = models.CharField(max_length=50, unique=True, verbose_name="Название")
    description = models.CharField(max_length=100, verbose_name="описание")
    caliber = models.CharField(max_length=10, null=True, blank=True, verbose_name="Калибр")
    barrel_length = models.IntegerField(default=2000, null=True, blank=True,
                                        verbose_name="Длина ствола")
    weight = models.IntegerField(default=2000, null=False, blank=False, verbose_name="Вес")
    price = models.IntegerField(default=2000, null=False, blank=False, verbose_name="Цена")

    CHOICES = (
        ('FR', 'Огнестрельное'),
        ('SA', 'Холодное'),
    )

    type = models.CharField(max_length=50, choices=CHOICES, verbose_name="Тип")

    image = models.ImageField(upload_to="image/gun/", null=False, blank=False,
                              verbose_name="Изображение")

    class Meta:
        verbose_name = "Оружие"
        verbose_name_plural = "Оружие"

    def __str__(self):
        return self.title

weapons/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from .models import Weapon


class AllWeaponsView(ListView):
    """Предстовление вывода всего оружия"""
    model = Weapon
    template_name = 'index.html'
    paginate_by = 5


class WeaponDetailView(DetailView):
    """Предстовление вывода оружия по id"""
    model = Weapon
    template_name = 'weapons/weapon_detail.html'


class Contact(TemplateView):
    template_name = 'contact.html'


def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

templates/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Магазин оружия</title>
  {% load static %}
	<link rel="stylesheet" href="{% static 'index/style.css' %}">
<!--  <link rel="shortcut icon" href="../image/лого.jpg" type="image/x-icon"/>-->
</head>

<body>
  <header>
    <div class="logo">
      <a href="{% url 'weapons:index' %}">Магазин оружия</a>
      <img class="logo1" src="{% static 'images/logo.jpg' %}" alt="connect">
    </div>
    <nav>
      <ul>
        <li><a href="{% url 'weapons:index' %}">Главная</a></li>
        <li>
          <a href="">Категории</a>
          <ul>
            <li><a href="">Огнестр. оружие</a></li>
            <li><a href="">Холодное оружие</a></li>
            <li><a href="">Охотничье оружие</a></li>
            <li><a href="">Другое</a></li>
          </ul>
        </li>
        <li>
          <a href="">Услуги</a>
          <ul>
            <li><a href="">Покупка</a></li>
            <li><a href="">Продажа</a></li>
            <li><a href="">Аренда</a></li>
            <li><a href="">Ремонт</a></li>
          </ul>
        </li>
        <li><a href="">Контакты</a></li>
      </ul>
    </nav>
  </header>
  <main>
    <block-content>
      <div class="content">
        <div class="block-left">
          <h1 class="text2"> Где мы находимся? </h1>
          <section class="map">
            <div class="container">
                <iframe
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d968.9615784189544!2d30.328833832423236!3d60.003325216322274!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46963475ee23888d%3A0xd2172d1004a4254f!2z0JXRgdGC0LXRgdGC0LLQtdC90L3Qvi3QndCw0YPRh9C90YvQuSDQm9C40YbQtdC5INCh0J_QsdCf0KM!5e0!3m2!1sru!2sru!4v1685034109982!5m2!1sru!2sru" allowfullscreen="" loading="lazy"
                  referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
            <h1 class="text2">Контакты:</h1>
            <div class="text2">
              <p>Магазин оружия: Пн-Вс, 10:00 - 21:00</p>
              <p>Интернет-магазин: Пн-Пт, 10:00 - 18:00</p>
              <p>Оружейная мастерская: Пн-Пт, 10:00 - 18:00 (необходима запись по телефону)</p>
              <div class="photo">
              <img src="../image/mail.jpg">
              </div>
              <p><a href="mailto:hwjr5479@gmail.com">moreInfo@gmail.com</a></p>

            </div>
          </section>
        </div>
        <div class="block-right">
          <h1 class="text2"> Почему мы?: </h1>
          <div class="text1">

            <p style="text-indent: 25px;">В нашей команде присутствуют только профессионалы своего дела,
              каждый в своем направлении. Увлеченные и стреляющие люди, которые имеют не только многолетний опыт работы
              в оружейной отрасли, но и желание помочь в любых вопросах, связанных с тюнингом оружия, подбора
              стрелкового снаряжения и средств для ухода, а также других всевозможных аксессуаров необходимых стрелку.
            </p>

            <p style="text-indent: 25px;" >Мы постоянно растем и адаптируемся, в зависимости от
              потребностей рынка и наших клиентов. Развиваемся вместе с Вами!</p>

            <p style="text-indent: 25px;" >Мы с радостью сотрудничаем с отечественными и зарубежными
              производителями, всегда в курсе новостей оружейного рынка России и мира. Получаем новые изделия одними из
              первых!</p>

            <img  class="photo" src="../image/магаз.jpg">

            <h2 class="text2" > МЫ РАБОТАЕМ ДЛЯ ВАС ЕЖЕДНЕВНО, БЕЗ ОБЕДА И ВЫХОДНЫХ С 10 ДО 21 ЧАСОВ. </h2>
            <p style="text-indent: 25px;" >Мы постоянно стремимся идти в ногу со временем. Мы создали
              совершенно новый концепт и взяли курс в сторону активных стрелков России. Спорт, тактические соревнования,
              развлекательная стрельба - это то, что нам нравится и то, чем мы занимаемся сами. Помимо кастомов и
              оружейного тюнинга Вы найдете у нас и другие товары, такие как спортивное стрелковое снаряжение и
              ассортимент приспособлений для релоадинга.</p>
            <p style="text-indent: 25px;" >Вы давно искали магазин в Петербурге, в котором можно получить
              полный комплекс товаров и услуг для стрельбы? Больше не нужно тратить время на поиски и платить за
              доставку с различных мест. Теперь Вы можете купить всё в одном месте, а также воспользоваться нашими
              услугами - получить всё, что необходимо Вам для эффективной стрельбы и достижения высочайших результатов.
              Уникальные кастомы в наличии, оружейный тюнинг, средства по уходу, снаряжение для стрельбы, а также прочие
              необходимые аксессуары для эффективной и комфортной стрельбы!</p>
          </div>
        </div>
      </div>
    </block-content>
  </main>
  <footer>
    <p>Магазин оружия &copy; 2023 Все права пользователей защищены</p>
  </footer>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Магазин оружия</title>
    {% load static %}
     <link rel="stylesheet" href="{% static 'index/style.css' %}">
  </head>
  <body>
    <header>
      <div class="logo">
        <a href="#">Магазин оружия</a>
      </div>
      <nav>
        <ul>
          <li><a href="#">Главная</a></li>
          <li>
            <a href="#">Категории</a>
            <ul>
              <li><a href="#">Огнестрельное оружие</a></li>
              <li><a href="#">Холодное оружие</a></li>
              <li><a href="#">Охотничье оружие</a></li>
              <li><a href="#">Другое</a></li>
            </ul>
          </li>
          <li><a href="{% url 'weapons:contact' %}">Контакты</a></li>
          <li>
            <a href="#">Услуги</a>
            <ul>
              <li><a href="#">Покупка</a></li>
              <li><a href="#">Продажа</a></li>
              <li><a href="#">Аренда</a></li>
              <li><a href="#">Ремонт</a></li>
            </ul>
          </li>
        </ul>
      </nav>
    </header>
    <main>
      <section class="hero-section">
        <h1>Лучшее оружие только у нас!</h1>
        <a href="#" class="btn">Узнать больше</a>
      </section>
      <div class="product-section">
{% block content %}
	<h2>Огнестрельное оружие</h2>
   {% if weapon_list %}
		{% for weapon in weapon_list %}
			{% if weapon.type == "FR" %}
		  <div class="product">
		     <img src="{{ weapon.image.url}}" alt="connect">
		  <p><a href="{% url 'weapons:weapon_info' weapon.id  %}">
                                     {{ weapon.title }}</a></p>
		    <p class="price">${{ weapon.price }}</p>
		    <a href="#" class="btn">Купить</a>
		  </div>
			{% endif %}
        {% endfor %}
	{% endif %}
{% endblock %}

<h2>Холодное оружие</h2>
{% if weapon_list %}
	{% for weapon in weapon_list %}
		{% if weapon.type == "SA" %}
		  <div class="product">
		     <img src="{{ weapon.image.url}}" alt="connect">
		    <p><a href="{% url 'weapons:weapon_info' weapon.id  %}">
                                     {{ weapon.title }}</a></p>
		    <p class="price">${{ weapon.price }}</p>
		    <a href="#" class="btn">Купить</a>
		  </div>
		{% endif %}
    {% endfor %}
{% endif %}
    <footer>
      <p>Магазин оружия &copy; 2022</p>
	  <p>Сайт создан Енгулатовым Ренатом</p>
    </footer>
      </div>
    </main>
  </body>
</html>

templates/weapons/weapon_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Магазин оружия</title>
  {% load static %}
   <link rel="stylesheet" href="{% static 'index/style.css' %}">
<!--  <link rel="shortcut icon" href="../image/лого.jpg" type="image/x-icon" />-->
</head>

<body>
  <header>
    <div class="logo">
      <a href="../index.html">Магазин оружия</a>
      <img class="logo1" src="{% static 'images/logo.jpg' %}" alt="connect">
    </div>
    <nav>
      <ul>
        <li><a href="{% url 'weapons:index' %}">Главная</a></li>
        <li>
          <a href="">Категории</a>
          <ul>
            <li><a href="">Огнестр. оружие</a></li>
            <li><a href="">Холодное оружие</a></li>
            <li><a href="">Охотничье оружие</a></li>
            <li><a href="">Другое</a></li>
          </ul>
        </li>
        <li>
          <a href="">Услуги</a>
          <ul>
            <li><a href="">Покупка</a></li>
            <li><a href="">Продажа</a></li>
            <li><a href="">Аренда</a></li>
            <li><a href="">Ремонт</a></li>
          </ul>
        </li>
        <li><a href="{% url 'weapons:contact' %}">Контакты</a></li>
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
          <div class="content">
            <div class="block-left">
              <h1 class="text2"> {{ weapon.title }} </h1>
                  <img  class="photo" src="{{ weapon.image.url}}" alt="connect">
                   <div class="text2">
                     <h1>Описание</h1></div>
                   <div class="text1">
                  <p>{{ weapon.description }}</p>
                 </div>
            </div>
            <div class="block-right">
            </div>
          </div>
    {% endblock %}
  </main>
  <footer>
    <p>Магазин оружия &copy; 2023 Все права пользователей защищены</p>
  </footer>
</body>

</html>